version: '3.8'

services:
  # Frontend Service (React App)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-builder
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:10000/api
      - REACT_APP_SOCKET_URL=http://localhost:10000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start

  # Backend Service (Node.js API)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-builder
    ports:
      - "10000:10000"
    environment:
      - NODE_ENV=production
      - PORT=10000
      - MONGODB_URI=mongodb://mongo:27017/jamalpur_chamber
      - JWT_SECRET=your-super-secure-jwt-secret-key-here
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    depends_on:
      - mongo
    command: npm start

  # MongoDB Service
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=jamalpur_chamber
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongo_data:
